baseURL = "https://markurusov1.github.io/defischolar_site/"         # we'll change this later for real deploy
languageCode = "en-us"
title = "DeFi Scholar"
theme = "ananke"

[params]
description = "High Schoolerâ€™s Guide to Decentralized Finance"
author = "markurusov1 & friends"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1